# Generated by Django 3.2.6 on 2021-08-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengenews', '0002_auto_20210814_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='first_paragraph',
            field=models.CharField(default='', max_length=64),
        ),
    ]
