# Generated by Django 3.2.6 on 2021-08-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengenews', '0003_articles_first_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='', max_length=30),
        ),
    ]
