# Generated by Django 3.2.6 on 2021-08-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengenews', '0004_articles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='', max_length=30, verbose_name='title-slug'),
        ),
    ]
