# Generated by Django 3.2.6 on 2021-08-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengenews', '0005_alter_articles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.CharField(default='', max_length=64),
        ),
    ]
